In [1]:
import numpy as np

#### Stage 1 : Huff model

In [15]:
# compute the probability of customers living at place i visiting a branch at site j

def P_ij(a, b, distance_ij, n):
    '''
    a: parameter that measures the relative attractiveness of branch j
    b: parameter that governs the shape of the distance decay function
    distance_ij: distance between customer i and branch j
    n: number of branches of the bank
    '''
    numerator = a / (distance_ij ** b)
    denominator = 0
    for j in range(1, n + 1):
        denominator += a / (distance_ij ** b)
    return numerator / denominator


#### Stage 2 : expected travel patterns

In [ ]:
#compute the expected travel patterns

def E_ij(a,b,distance_ij,n,consumers):
    '''
    consumers: number of consumers living at place i
    '''
    return consumers*P_ij(a,b,distance_ij,n)

#### Stage 3 : expected patronage at each branch

In [ ]:
# compute the total expected number of consumers within the region who are likely to patronize branch j

def T_j(a,b,distance_ij,n,consumers):
    total = 0
    for i in range(1,len(consumers)+1):
        total += E_ij(a,b,distance_ij,n,consumers[i-1])
    return total

## Application

#### Stage 1

In [ ]:
a=1

In [8]:
# Define existing Orabank agency data
agencies_orabank = [
    {"name": "Orabank Agence principale", "address": "Avenue Charles De Gaulle, N'Djamena, Chad"},
    {"name": "Orabank Agence de Djambal Bahr", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "Orabank Agence Amriguébé", "address": "Boulevard François Tombalbaye, N'Djamena, Chad"},
    {"name": "Orabank Agence V.I.P", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "Orabank Agence Abéché", "address": "Abéché, Chad"},
    {"name": "Orabank Agence Moundou", "address": "Moundou, Chad"},
    {"name": "Orabank Agence Sarh", "address": "Sarh, Chad"},
    {"name": "Orabank Agence Am Timan", "address": "Am Timan, Chad"},
    {"name": "Orabank Agence Pala", "address": "Pala, Chad"},
    {"name": "Orabank Agence Mongo", "address": "Mongo, Chad"}
]

# Define new Ecobank agency data
agencies_ecobank = [
    {"name": "Ecobank Agence principale", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "Ecobank Agence Rue de 40m", "address": "Boulevard François Tombalbaye, N'Djamena, Chad"},
    {"name": "Ecobank Agence Paris Congo", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "Ecobank Agence Goudji", "address": "Goudji, N'Djamena, Chad"},
    {"name": "Ecobank Agence Chagoua", "address": "Chagoua, N'Djamena, Chad"},
    {"name": "Ecobank Agence Moundou", "address": "Moundou, Chad"},
    {"name": "Ecobank Agence Pala", "address": "Pala, Chad"},
    {"name": "Ecobank Agence Sarh", "address": "Sarh, Chad"},
    {"name": "Ecobank Agence Doba", "address": "Doba, Chad"},
    {"name": "Ecobank Agence Abéché", "address": "Abéché, Chad"},
    {"name": "Ecobank Agence Bongor", "address": "Bongor, Chad"}
]

# Define Coris Bank agency data
agencies_coris = [
    {"name": "Coris Bank Agence VIP", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "Coris Bank Agence Rue de 40M", "address": "Rue de 40m, N'Djamena, Chad"},
    {"name": "Coris Bank Agence Centrale", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "Coris Bank Agence Chagoua", "address": "Chagoua, N'Djamena, Chad"},
    {"name": "Coris Bank Agence El Niméry", "address": "Avenue Nimery, N'Djamena, Chad"},
    {"name": "Coris Bank Agence Farcha", "address": "Farcha, N'Djamena, Chad"},
    {"name": "Coris Bank Agence Hamama", "address": "Hamama, N'Djamena, Chad"},
    {"name": "Coris Bank Agence Kabalaye", "address": "Kabalaye, N'Djamena, Chad"},
    {"name": "Coris Bank Agence Abéché", "address": "Abéché, Chad"},
    {"name": "Coris Bank Agence Mongo", "address": "Mongo, Chad"},
    {"name": "Coris Bank Agence Doba", "address": "Doba, Chad"},
    {"name": "Coris Bank Agence Moundou", "address": "Moundou, Chad"},
    {"name": "Coris Bank Agence Sarh", "address": "Sarh, Chad"}
]

# Define UBA agency data
agencies_uba = [
    {"name": "UBA Agence principale", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "UBA Agence Farcha", "address": "Farcha, N'Djamena, Chad"},
    {"name": "UBA Agence Sabangali", "address": "Sabangali, N'Djamena, Chad"},
    {"name": "UBA Agence Dembé", "address": "Dembé, N'Djamena, Chad"},
    {"name": "UBA Agence Ndjari", "address": "Ndjari, N'Djamena, Chad"},
    {"name": "UBA Agence Gassi", "address": "Gassi, N'Djamena, Chad"}
]

# Define BAC agency data
agencies_bac = [
    {"name": "BAC Agence principale", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
]

# Define BCC agency data
agencies_bcc = [
    {"name": "BCC Agence principale", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "BCC Agence Rue de 40", "address": "Rue de 40m, N'Djamena, Chad"},
    {"name": "BCC Agence Al Yousr", "address": "Avenue Nimery, N'Djamena, Chad"},
    {"name": "BCC Agence Hamama", "address": "Hamama, N'Djamena, Chad"},
    {"name": "BCC Agence Ambassatna", "address": "Ambassatna, N'Djamena, Chad"},
    {"name": "BCC Agence Tiné", "address": "Tiné, Chad"},
    {"name": "BCC Agence Moundou", "address": "Moundou, Chad"},
    {"name": "BCC Agence Abéché", "address": "Abéché, Chad"}
]

# Define CBT agency data
agencies_cbt = [
    {"name": "CBT Agence principale", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "CBT Agence Rue de 40", "address": "Rue de 40m, N'Djamena, Chad"},
    {"name": "CBT Agence Al Yousr", "address": "Avenue Nimery, N'Djamena, Chad"},
    {"name": "CBT Agence Aéroport", "address": "Aéroport, N'Djamena, Chad"},
    {"name": "CBT Agence Ngueli", "address": "Ngueli, N'Djamena, Chad"},
    {"name": "CBT Agence Moundou", "address": "Moundou, Chad"},
    {"name": "CBT Agence Abéché", "address": "Abéché, Chad"}
]

# Define BSIC agency data
agencies_bsic = [
    {"name": "BSIC Agence principale", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "BSIC Agence Habbena", "address": "N'Djamena, Chad"},
    {"name": "BSIC Agence Maldom Bada", "address": "Avenue Nimery, N'Djamena, Chad"},
    {"name": "BSIC Agence Marché à Mil", "address": "N'Djamena, Chad"},
    {"name": "BSIC Agence CDG", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"},
    {"name": "BSIC Agence Dembé", "address": "Dembé, N'Djamena, Chad"},
    {"name": "BSIC Agence Abéché", "address": "Abéché, Chad"},
    {"name": "BSIC Agence Bol", "address": "Bol, Chad"},
    {"name": "BSIC Agence Mao", "address": "Mao, Chad"},
    {"name": "BSIC Agence Moundou", "address": "Moundou, Chad"}
]

# Define BHT agency data
agencies_bht = [
    {"name": "BHT Agence principale", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"}
]

# Define Attijari agency data
agencies_attijari = [
    {"name": "Attijari Agence principale", "address": "Avenue Charles de Gaulle, N'Djamena, Chad"}
]

In [16]:
# Define the mapping of cities to their regions
city_to_region = {
    "N'Djamena": "N'Djamena",
    "Abéché": "Ouaddaï",
    "Moundou": "Logone Occidental",
    "Sarh": "Moyen-Chari",
    "Am Timan": "Salamat",
    "Pala": "Mayo-Kebbi Ouest",
    "Mongo": "Guéra",
    "Doba": "Logone Oriental",
    "Bongor": "Mayo-Kebbi Est",
    "Tiné": "Wadi Fira",
    "Bol": "Lac",
    "Mao": "Kanem",
    "Moussoro": "Barh-El-Gazel",
    "Ati": "Batha",
    "Faya-Largeau": "Borkou",
    "Massenya": "Chari-Baguirmi",
    "Am-Djarass": "Ennedi Est",
    "Fada": "Ennedi Ouest",
    "Massakory": "Hadjer-Lamis",
    "Koumra": "Mandoul",
    "Goz Beïda": "Sila",
    "Kélo": "Tandjilé",
    "Bardaï": "Tibesti",
}


In [23]:
#dictionnary of the area of the different regions

area_regions = {
    "N'Djamena": 21.8,
    "Ouaddaï": 76.8,
    "Logone Occidental": 40.2,
    "Moyen-Chari": 40.3,
    "Salamat": 53.3,
    "Mayo-Kebbi Ouest": 30.7,
    "Guéra": 18.9,
    "Logone Oriental": 27.0,
    "Mayo-Kebbi Est": 29.7,
    "Wadi Fira": 61.3,
    "Lac": 23.3,
    "Kanem": 155.4,
    "Barh-El-Gazel": 86.2,
    "Batha": 64.7,
    "Borkou": 61.3,
    "Chari-Baguirmi": 44.9,
    "Ennedi Est": 61.0,
    "Ennedi Ouest": 96.7,
    "Hadjer-Lamis": 16.1,
    "Mandoul": 22.1,
    "Sila": 25.5,
    "Tandjilé": 11.9,
    "Tibesti": 153.4,
}

In [21]:
# Compile all agency data into a single structure
all_agencies = {
    "Orabank": agencies_orabank,
    "Ecobank": agencies_ecobank,
    "Coris Bank": agencies_coris,
    "UBA": agencies_uba,
    "BAC": agencies_bac,
    "BCC": agencies_bcc,
    "CBT": agencies_cbt,
    "BSIC": agencies_bsic,
    "BHT": agencies_bht,
    "Attijari": agencies_attijari,
}

# Initialize the matrix with zeros for each region
branch_matrix = {bank: {region: 0 for region in set(city_to_region.values())} for bank in all_agencies.keys()}

# Populate the matrix with branch counts based on city-to-region mapping
for bank, agencies in all_agencies.items():
    for agency in agencies:
        # Extract the city from the agency's address
        # Assuming city is the first part of the address before the comma
        city = agency["address"].split(",")[-2].strip()
        
        # Check if the city is in the mapping
        if city in city_to_region:
            region = city_to_region[city]
            branch_matrix[bank][region] += 1
        else:
            print(f"City not found in mapping for agency: {agency['name']} - {agency['address']}")



# Define the banks and regions
banks = list(all_agencies.keys())  # Get the list of banks
regions = list(city_to_region.values())  # Get the list of unique regions

# Create a mapping for banks and regions to indices
bank_indices = {bank: idx for idx, bank in enumerate(banks)}
region_indices = {region: idx for idx, region in enumerate(set(regions))}

# Initialize the NumPy array with zeros
branch_matrix = np.zeros((len(banks), len(region_indices)), dtype=int)

# Fill the branch matrix with counts
for bank, agencies in all_agencies.items():
    for agency in agencies:
        # Extract the city from the agency's address
        city = agency["address"].split(",")[-2].strip()
        if city in city_to_region:
            region = city_to_region[city]
            # Increment the branch count for the respective bank and region
            branch_matrix[bank_indices[bank], region_indices[region]] += 1
        else:
            print(f"City not found in mapping for agency: {agency['name']} - {agency['address']}")

# Now branch_matrix contains the counts
print("Branch Matrix:")
print(branch_matrix)


Branch Matrix:
[[0 0 0 1 0 0 1 1 0 0 4 0 0 0 1 0 0 0 0 1 0 1 0]
 [0 1 0 1 0 0 1 1 0 0 5 0 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1 0 0 8 0 0 0 1 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 6 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 5 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 5 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 6 1 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]


In [19]:
distances={"N'Djamena": {'Abéché': 654.2560670210189, 'Moundou': 410.70377788312476, 'Sarh': 493.1279663830866, 'Am Timan': 582.4578962460926, 'Pala': 306.4909676503545, 'Mongo': 395.08504565320175, 'Doba': 432.3372447133508, 'Bongor': 207.30198848148913, 'Tiné': 897.216892424752, 'Bol': 154.30519495055103, 'Mao': 224.64313298692068, 'Moussoro': 492.8337447591511, 'Ati': 377.00008357013365, 'Faya-Largeau': 777.632824032352, 'Massenya': 145.75585823272175, 'Am-Djarass': 947.1669798561358, 'Fada': 900.8465254021704, 'Massakory': 122.6309133714496, 'Koumra': 448.5119730730808, 'Goz Beïda': 691.3742146107828, 'Kélo': 322.187852469485, 'Bardaï': 1047.704757206416}, 'Abéché': {"N'Djamena": 654.2560670210188, 'Moundou': 781.7755786754406, 'Sarh': 584.8070502505899, 'Am Timan': 315.66629346060347, 'Pala': 813.3351459770988, 'Mongo': 295.5816392735892, 'Doba': 719.7786247668054, 'Bongor': 712.3965437994094, 'Tiné': 250.19971330907484, 'Bol': 661.8412552255138, 'Mao': 596.2506846257811, 'Moussoro': 706.9478553057605, 'Ati': 277.62446314982304, 'Faya-Largeau': 491.3904221499436, 'Massenya': 572.6637449108692, 'Am-Djarass': 329.2589465248401, 'Fada': 382.7701515990653, 'Massakory': 558.6104207793554, 'Koumra': 652.5150156089129, 'Goz Beïda': 189.00124777462594, 'Kélo': 743.919862628139, 'Bardaï': 929.9477766194051}, 'Moundou': {"N'Djamena": 410.7037778831248, 'Abéché': 781.7755786754406, 'Sarh': 262.7954698552767, 'Am Timan': 536.9586147443111, 'Pala': 155.81452139327573, 'Mongo': 493.36410943933515, 'Doba': 86.38733296468091, 'Bongor': 205.80108920111297, 'Tiné': 1025.0243364723315, 'Bol': 564.9185846268163, 'Mao': 623.5849823605139, 'Moussoro': 155.70604137997805, 'Ati': 572.8806120971147, 'Faya-Largeau': 1090.3501283241642, 'Massenya': 315.7372950495823, 'Am-Djarass': 1110.9658881845519, 'Fada': 1129.583901081106, 'Massakory': 494.096021508258, 'Koumra': 166.69406841088255, 'Goz Beïda': 711.4297745029241, 'Kélo': 88.94651299501336, 'Bardaï': 1425.590476435497}, 'Sarh': {"N'Djamena": 493.1279663830866, 'Abéché': 584.8070502505899, 'Moundou': 262.79546985527674, 'Am Timan': 295.5371261198269, 'Pala': 383.19302174599926, 'Mongo': 339.91859923739435, 'Doba': 177.44061240269514, 'Bongor': 354.72704117964554, 'Tiné': 810.6309158900024, 'Bol': 626.3901982762018, 'Mao': 647.7971132229867, 'Moussoro': 131.07949795388, 'Ati': 452.8161647792554, 'Faya-Largeau': 979.2590214025195, 'Massenya': 349.84416701160643, 'Am-Djarass': 908.2894903993173, 'Fada': 959.478062427131, 'Massakory': 517.6688316100827, 'Koumra': 96.11974421970075, 'Goz Beïda': 475.6792210494517, 'Kélo': 286.75823545966614, 'Bardaï': 1366.332938692875}, 'Am Timan': {"N'Djamena": 582.4578962460926, 'Abéché': 315.6662934606035, 'Moundou': 536.958614744311, 'Sarh': 295.53712611982684, 'Pala': 616.7065832130876, 'Mongo': 215.6591641975576, 'Doba': 459.50869553273503, 'Bongor': 543.2580975410564, 'Tiné': 520.1734886122028, 'Bol': 662.4995015646708, 'Mao': 639.2346529140144, 'Moussoro': 426.1187906763102, 'Ati': 320.9211697978036, 'Faya-Largeau': 775.7553629781568, 'Massenya': 450.16911782477905, 'Am-Djarass': 623.2830151391615, 'Fada': 698.3991813492783, 'Massakory': 540.319122606155, 'Koumra': 381.17772711781686, 'Goz Beïda': 180.19267698071272, 'Kélo': 528.1194414918028, 'Bardaï': 1199.1864902734003}, 'Pala': {"N'Djamena": 306.4909676503545, 'Abéché': 813.3351459770988, 'Moundou': 155.8145213932756, 'Sarh': 383.19302174599926, 'Am Timan': 616.7065832130876, 'Mongo': 517.8237874406382, 'Doba': 227.5250798441216, 'Bongor': 113.65581695520872, 'Tiné': 1062.9393765230614, 'Bol': 456.54829214633486, 'Mao': 530.7686374302557, 'Moussoro': 302.4838567191849, 'Ati': 568.107428742824, 'Faya-Largeau': 1053.0713365087242, 'Massenya': 265.25876404829813, 'Am-Djarass': 1137.099471125091, 'Fada': 1130.3752586219152, 'Massakory': 413.57261019036207, 'Koumra': 293.85775624086807, 'Goz Beïda': 777.8740076159946, 'Kélo': 96.43484640907224, 'Bardaï': 1351.7165067926326}, 'Mongo': {"N'Djamena": 395.08504565320175, 'Abéché': 295.58163927358913, 'Moundou': 493.36410943933515, 'Sarh': 339.91859923739435, 'Am Timan': 215.65916419755766, 'Pala': 517.8237874406382, 'Doba': 440.1058141096597, 'Bongor': 418.6842156521812, 'Tiné': 545.1533815195935, 'Bol': 453.4354437529401, 'Mao': 424.1366678420644, 'Moussoro': 442.5294107741928, 'Ati': 120.29566473990327, 'Faya-Largeau': 639.4143358725305, 'Massenya': 286.91044983230927, 'Am-Djarass': 621.7552962730532, 'Fada': 638.1433692217266, 'Massakory': 332.5557341787414, 'Koumra': 383.7474130854938, 'Goz Beïda': 296.2958819101765, 'Kélo': 449.49774433929963, 'Bardaï': 1035.329683579614}, 'Doba': {"N'Djamena": 432.33724471335097, 'Abéché': 719.7786247668053, 'Moundou': 86.38733296468091, 'Sarh': 177.44061240269505, 'Am Timan': 459.50869553273515, 'Pala': 227.52507984412154, 'Mongo': 440.10581410965955, 'Bongor': 242.86729546066397, 'Tiné': 958.5500134303506, 'Bol': 583.3969983833604, 'Mao': 630.4246897885397, 'Moussoro': 75.06416673121673, 'Ati': 531.6491193116369, 'Faya-Largeau': 1057.9683712149895, 'Massenya': 314.1324676323274, 'Am-Djarass': 1048.6815520131447, 'Fada': 1078.1411001319238, 'Massakory': 497.5184603807417, 'Koumra': 81.54360986046662, 'Goz Beïda': 636.7279928614134, 'Kélo': 137.92368707417765, 'Bardaï': 1411.792160889918}, 'Bongor': {"N'Djamena": 207.3019884814891, 'Abéché': 712.3965437994094, 'Moundou': 205.8010892011131, 'Sarh': 354.72704117964554, 'Am Timan': 543.2580975410564, 'Pala': 113.65581695520878, 'Mongo': 418.6842156521812, 'Doba': 242.86729546066388, 'Tiné': 962.586926041432, 'Bol': 361.4065951209584, 'Mao': 427.2377949480842, 'Moussoro': 312.8414269483149, 'Ati': 458.9303884317078, 'Faya-Largeau': 939.4545400794342, 'Massenya': 152.31794034517836, 'Am-Djarass': 1032.497609727118, 'Fada': 1019.7456453653923, 'Massakory': 304.46374312627097, 'Koumra': 282.66645957704156, 'Goz Beïda': 693.1013780753144, 'Kélo': 116.8894319087429, 'Bardaï': 1243.5263356637638}, 'Tiné': {"N'Djamena": 897.216892424752, 'Abéché': 250.19971330907495, 'Moundou': 1025.0243364723312, 'Sarh': 810.6309158900024, 'Am Timan': 520.1734886122031, 'Pala': 1062.9393765230614, 'Mongo': 545.1533815195933, 'Doba': 958.5500134303509, 'Bongor': 962.586926041432, 'Bol': 887.8543685972884, 'Mao': 811.5667470446141, 'Moussoro': 938.104075210514, 'Ati': 521.0062872275907, 'Faya-Largeau': 509.023144179768, 'Massenya': 822.2326391594833, 'Am-Djarass': 115.66019171839797, 'Fada': 273.521351584841, 'Massakory': 794.3257322099668, 'Koumra': 886.9272580329856, 'Goz Beïda': 345.54428818563525, 'Kélo': 991.5652815321195, 'Bardaï': 932.3199809097401}, 'Bol': {"N'Djamena": 154.30519495055088, 'Abéché': 661.8412552255137, 'Moundou': 564.9185846268163, 'Sarh': 626.3901982762018, 'Am Timan': 662.4995015646707, 'Pala': 456.5482921463347, 'Mongo': 453.4354437529401, 'Doba': 583.3969983833606, 'Bongor': 361.4065951209583, 'Tiné': 887.8543685972884, 'Mao': 97.28984369175578, 'Moussoro': 640.5504321940047, 'Ati': 393.25599962724334, 'Faya-Largeau': 681.9080354673486, 'Massenya': 278.8106972707882, 'Am-Djarass': 919.5894280075, 'Fada': 844.7497886898849, 'Massakory': 122.2559475986469, 'Koumra': 592.7029798510799, 'Goz Beïda': 738.8833891080812, 'Kélo': 476.4795321078271, 'Bardaï': 909.8857209459118}, 'Mao': {"N'Djamena": 224.64313298692068, 'Abéché': 596.2506846257811, 'Moundou': 623.5849823605139, 'Sarh': 647.7971132229867, 'Am Timan': 639.2346529140144, 'Pala': 530.7686374302557, 'Mongo': 424.1366678420643, 'Doba': 630.4246897885398, 'Bongor': 427.2377949480843, 'Tiné': 811.566747044614, 'Bol': 97.28984369175575, 'Moussoro': 680.3456259403464, 'Ati': 342.5629955978605, 'Faya-Largeau': 584.656426913094, 'Massenya': 316.54648486860214, 'Am-Djarass': 836.0924116120528, 'Fada': 753.045871551426, 'Massakory': 133.4298696094592, 'Koumra': 627.9082217071324, 'Goz Beïda': 693.2136834471564, 'Kélo': 537.3430526572031, 'Bardaï': 823.7483895847574}, 'Moussoro': {"N'Djamena": 492.8337447591511, 'Abéché': 706.9478553057604, 'Moundou': 155.70604137997805, 'Sarh': 131.07949795387998, 'Am Timan': 426.1187906763103, 'Pala': 302.483856719185, 'Mongo': 442.5294107741928, 'Doba': 75.06416673121677, 'Bongor': 312.84142694831496, 'Tiné': 938.104075210514, 'Bol': 640.5504321940047, 'Mao': 680.3456259403466, 'Ati': 544.9271612413671, 'Faya-Largeau': 1074.6156726214922, 'Massenya': 364.77318268965917, 'Am-Djarass': 1033.326937087728, 'Fada': 1075.4851466036896, 'Massakory': 546.9198708716601, 'Koumra': 59.8028597143706, 'Goz Beïda': 606.0660861615914, 'Kélo': 212.50807928223895, 'Bardaï': 1443.0406200498237}, 'Ati': {"N'Djamena": 377.00008357013365, 'Abéché': 277.62446314982304, 'Moundou': 572.8806120971146, 'Sarh': 452.8161647792554, 'Am Timan': 320.9211697978036, 'Pala': 568.1074287428239, 'Mongo': 120.29566473990332, 'Doba': 531.6491193116367, 'Bongor': 458.9303884317078, 'Tiné': 521.0062872275909, 'Bol': 393.2559996272434, 'Mao': 342.5629955978605, 'Moussoro': 544.9271612413671, 'Faya-Largeau': 529.7623493017803, 'Massenya': 309.7266343807031, 'Am-Djarass': 578.383639178653, 'Fada': 562.8811361086541, 'Massakory': 283.11547163931004, 'Koumra': 485.1875402671546, 'Goz Beïda': 350.6538384230686, 'Kélo': 515.2022364312154, 'Bardaï': 916.4655035043642}, 'Faya-Largeau': {"N'Djamena": 777.6328240323521, 'Abéché': 491.39042214994345, 'Moundou': 1090.3501283241644, 'Sarh': 979.2590214025195, 'Am Timan': 775.7553629781565, 'Pala': 1053.0713365087245, 'Mongo': 639.4143358725304, 'Doba': 1057.9683712149897, 'Bongor': 939.4545400794344, 'Tiné': 509.0231441797678, 'Bol': 681.9080354673486, 'Mao': 584.6564269130943, 'Moussoro': 1074.6156726214922, 'Ati': 529.7623493017803, 'Massenya': 789.9360631557086, 'Am-Djarass': 447.9492125124293, 'Fada': 275.69823992172064, 'Massakory': 655.3165045030663, 'Koumra': 1014.8448443967036, 'Goz Beïda': 680.2735966611717, 'Kélo': 1021.5623055256151, 'Bardaï': 440.3582739156148}, 'Massenya': {"N'Djamena": 145.7558582327218, 'Abéché': 572.6637449108691, 'Moundou': 315.7372950495824, 'Sarh': 349.8441670116066, 'Am Timan': 450.16911782477905, 'Pala': 265.25876404829813, 'Mongo': 286.9104498323092, 'Doba': 314.13246763232746, 'Bongor': 152.3179403451784, 'Tiné': 822.2326391594833, 'Bol': 278.8106972707883, 'Mao': 316.5464848686022, 'Moussoro': 364.77318268965917, 'Ati': 309.7266343807031, 'Faya-Largeau': 789.9360631557083, 'Am-Djarass': 886.8313881871129, 'Fada': 868.23986361398, 'Massakory': 183.4093859920764, 'Koumra': 314.6269439840946, 'Goz Beïda': 577.3991843544767, 'Kélo': 236.15914340909018, 'Bardaï': 1110.0873509312762}, 'Am-Djarass': {"N'Djamena": 947.1669798561358, 'Abéché': 329.25894652483987, 'Moundou': 1110.965888184552, 'Sarh': 908.2894903993171, 'Am Timan': 623.2830151391613, 'Pala': 1137.099471125091, 'Mongo': 621.755296273053, 'Doba': 1048.6815520131447, 'Bongor': 1032.4976097271183, 'Tiné': 115.66019171839801, 'Bol': 919.5894280075003, 'Mao': 836.0924116120528, 'Moussoro': 1033.3269370877279, 'Ati': 578.3836391786531, 'Faya-Largeau': 447.9492125124294, 'Massenya': 886.831388187113, 'Fada': 183.13879837552133, 'Massakory': 836.8822287639754, 'Koumra': 980.1029939258043, 'Goz Beïda': 453.8491747963023, 'Kélo': 1071.2425211182765, 'Bardaï': 850.3104863298968}, 'Fada': {"N'Djamena": 900.8465254021704, 'Abéché': 382.7701515990651, 'Moundou': 1129.5839010811062, 'Sarh': 959.4780624271309, 'Am Timan': 698.399181349278, 'Pala': 1130.3752586219152, 'Mongo': 638.1433692217266, 'Doba': 1078.1411001319238, 'Bongor': 1019.7456453653921, 'Tiné': 273.5213515848411, 'Bol': 844.7497886898849, 'Mao': 753.045871551426, 'Moussoro': 1075.4851466036894, 'Ati': 562.881136108654, 'Faya-Largeau': 275.69823992172064, 'Massenya': 868.2398636139803, 'Am-Djarass': 183.1387983755213, 'Massakory': 781.967448499689, 'Koumra': 1018.3249977604953, 'Goz Beïda': 552.6642104058476, 'Kélo': 1077.1420437039224, 'Bardaï': 667.2316707315963}, 'Massakory': {"N'Djamena": 122.63091337144967, 'Abéché': 558.6104207793554, 'Moundou': 494.09602150825805, 'Sarh': 517.6688316100826, 'Am Timan': 540.319122606155, 'Pala': 413.572610190362, 'Mongo': 332.55573417874143, 'Doba': 497.5184603807416, 'Bongor': 304.4637431262709, 'Tiné': 794.3257322099668, 'Bol': 122.25594759864687, 'Mao': 133.42986960945922, 'Moussoro': 546.91987087166, 'Ati': 283.11547163931004, 'Faya-Largeau': 655.3165045030661, 'Massenya': 183.40938599207632, 'Am-Djarass': 836.8822287639754, 'Fada': 781.9674484996892, 'Koumra': 494.699449788411, 'Goz Beïda': 621.7555224942166, 'Kélo': 409.5684891102041, 'Bardaï': 939.0728698245164}, 'Koumra': {"N'Djamena": 448.5119730730809, 'Abéché': 652.515015608913, 'Moundou': 166.69406841088258, 'Sarh': 96.11974421970072, 'Am Timan': 381.177727117817, 'Pala': 293.85775624086807, 'Mongo': 383.747413085494, 'Doba': 81.54360986046659, 'Bongor': 282.6664595770416, 'Tiné': 886.9272580329857, 'Bol': 592.7029798510799, 'Mao': 627.9082217071324, 'Moussoro': 59.80285971437074, 'Ati': 485.1875402671546, 'Faya-Largeau': 1014.8448443967036, 'Massenya': 314.6269439840946, 'Am-Djarass': 980.1029939258041, 'Fada': 1018.3249977604953, 'Massakory': 494.69944978841096, 'Goz Beïda': 559.7999155144119, 'Kélo': 198.23843137095014, 'Bardaï': 1384.068096127482}, 'Goz Beïda': {"N'Djamena": 691.3742146107828, 'Abéché': 189.00124777462585, 'Moundou': 711.4297745029241, 'Sarh': 475.67922104945166, 'Am Timan': 180.19267698071258, 'Pala': 777.8740076159946, 'Mongo': 296.2958819101765, 'Doba': 636.7279928614134, 'Bongor': 693.1013780753144, 'Tiné': 345.5442881856355, 'Bol': 738.8833891080812, 'Mao': 693.2136834471565, 'Moussoro': 606.0660861615914, 'Ati': 350.6538384230685, 'Faya-Largeau': 680.2735966611716, 'Massenya': 577.3991843544767, 'Am-Djarass': 453.84917479630235, 'Fada': 552.6642104058475, 'Massakory': 621.7555224942166, 'Koumra': 559.799915514412, 'Kélo': 694.3076590456853, 'Bardaï': 1118.1541838985706}, 'Kélo': {"N'Djamena": 322.187852469485, 'Abéché': 743.9198626281388, 'Moundou': 88.94651299501334, 'Sarh': 286.7582354596661, 'Am Timan': 528.119441491803, 'Pala': 96.43484640907224, 'Mongo': 449.49774433929963, 'Doba': 137.9236870741775, 'Bongor': 116.88943190874295, 'Tiné': 991.5652815321195, 'Bol': 476.4795321078269, 'Mao': 537.3430526572032, 'Moussoro': 212.50807928223898, 'Ati': 515.2022364312153, 'Faya-Largeau': 1021.5623055256153, 'Massenya': 236.15914340909018, 'Am-Djarass': 1071.2425211182765, 'Fada': 1077.1420437039224, 'Massakory': 409.568489110204, 'Koumra': 198.23843137095008, 'Goz Beïda': 694.3076590456855, 'Bardaï': 1345.2298732933796}, 'Bardaï': {"N'Djamena": 1047.7047572064157, 'Abéché': 929.9477766194051, 'Moundou': 1425.590476435497, 'Sarh': 1366.332938692875, 'Am Timan': 1199.1864902734005, 'Pala': 1351.7165067926326, 'Mongo': 1035.329683579614, 'Doba': 1411.7921608899178, 'Bongor': 1243.5263356637638, 'Tiné': 932.3199809097401, 'Bol': 909.8857209459118, 'Mao': 823.7483895847577, 'Moussoro': 1443.040620049824, 'Ati': 916.4655035043644, 'Faya-Largeau': 440.3582739156148, 'Massenya': 1110.0873509312762, 'Am-Djarass': 850.3104863298964, 'Fada': 667.2316707315964, 'Massakory': 939.0728698245166, 'Koumra': 1384.068096127482, 'Goz Beïda': 1118.1541838985706, 'Kélo': 1345.2298732933796}}

In [22]:
# Extract the regions
regions = list(distances.keys())

# Initialize the distance matrix with zeros
n = len(regions)
distance_matrix = np.zeros((n, n))

# Fill the distance matrix
for i in range(n):
    for j in range(n):
        if i == j:
            distance_matrix[i][j] = 0  # Distance to self is zero
        else:
            distance_matrix[i][j] = distances[regions[i]].get(regions[j], np.nan)  # Use NaN if no distance found

# Print the distance matrix
print("Distance Matrix:")
print(distance_matrix)

#map the regions to indices
region_indices = {region: idx for idx, region in enumerate(regions)}

print(region_indices)

Distance Matrix:
[[   0.          654.25606702  410.70377788  493.12796638  582.45789625
   306.49096765  395.08504565  432.33724471  207.30198848  897.21689242
   154.30519495  224.64313299  492.83374476  377.00008357  777.63282403
   145.75585823  947.16697986  900.8465254   122.63091337  448.51197307
   691.37421461  322.18785247 1047.70475721]
 [ 654.25606702    0.          781.77557868  584.80705025  315.66629346
   813.33514598  295.58163927  719.77862477  712.3965438   250.19971331
   661.84125523  596.25068463  706.94785531  277.62446315  491.39042215
   572.66374491  329.25894652  382.7701516   558.61042078  652.51501561
   189.00124777  743.91986263  929.94777662]
 [ 410.70377788  781.77557868    0.          262.79546986  536.95861474
   155.81452139  493.36410944   86.38733296  205.8010892  1025.02433647
   564.91858463  623.58498236  155.70604138  572.8806121  1090.35012832
   315.73729505 1110.96588818 1129.58390108  494.09602151  166.69406841
   711.4297745    88.946513  